In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
## Define the vocabulary size
voc_size=10000

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[7652, 9991, 1534, 5876],
 [7652, 9991, 1534, 1631],
 [7652, 4498, 1534, 3412],
 [3243, 9225, 8515, 2767, 2652],
 [3243, 9225, 8515, 2767, 5386],
 [9699, 7652, 975, 1534, 9393],
 [5600, 4580, 9217, 2767]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 7652 9991 1534 5876]
 [   0    0    0    0 7652 9991 1534 1631]
 [   0    0    0    0 7652 4498 1534 3412]
 [   0    0    0 3243 9225 8515 2767 2652]
 [   0    0    0 3243 9225 8515 2767 5386]
 [   0    0    0 9699 7652  975 1534 9393]
 [   0    0    0    0 5600 4580 9217 2767]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 369ms/step


array([[[ 0.04736415,  0.03354922,  0.0032799 , -0.03189936,
         -0.0288673 ,  0.03545895, -0.00468605, -0.03094945,
         -0.0467746 ,  0.04371128],
        [ 0.04736415,  0.03354922,  0.0032799 , -0.03189936,
         -0.0288673 ,  0.03545895, -0.00468605, -0.03094945,
         -0.0467746 ,  0.04371128],
        [ 0.04736415,  0.03354922,  0.0032799 , -0.03189936,
         -0.0288673 ,  0.03545895, -0.00468605, -0.03094945,
         -0.0467746 ,  0.04371128],
        [ 0.04736415,  0.03354922,  0.0032799 , -0.03189936,
         -0.0288673 ,  0.03545895, -0.00468605, -0.03094945,
         -0.0467746 ,  0.04371128],
        [-0.02076002, -0.023086  ,  0.03959519, -0.04082254,
         -0.0348482 ,  0.03547755, -0.00478543, -0.04081295,
         -0.0077992 , -0.04996519],
        [-0.01928884,  0.03266681,  0.006497  ,  0.03460497,
          0.00040847,  0.04024297,  0.00299785, -0.016659  ,
          0.01111599, -0.01404827],
        [ 0.0468406 ,  0.01928278,  0.01705045, -0.0

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 7652, 9991, 1534, 5876])

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 71ms/step


array([[ 0.04736415,  0.03354922,  0.0032799 , -0.03189936, -0.0288673 ,
         0.03545895, -0.00468605, -0.03094945, -0.0467746 ,  0.04371128],
       [ 0.04736415,  0.03354922,  0.0032799 , -0.03189936, -0.0288673 ,
         0.03545895, -0.00468605, -0.03094945, -0.0467746 ,  0.04371128],
       [ 0.04736415,  0.03354922,  0.0032799 , -0.03189936, -0.0288673 ,
         0.03545895, -0.00468605, -0.03094945, -0.0467746 ,  0.04371128],
       [ 0.04736415,  0.03354922,  0.0032799 , -0.03189936, -0.0288673 ,
         0.03545895, -0.00468605, -0.03094945, -0.0467746 ,  0.04371128],
       [-0.02076002, -0.023086  ,  0.03959519, -0.04082254, -0.0348482 ,
         0.03547755, -0.00478543, -0.04081295, -0.0077992 , -0.04996519],
       [-0.01928884,  0.03266681,  0.006497  ,  0.03460497,  0.00040847,
         0.04024297,  0.00299785, -0.016659  ,  0.01111599, -0.01404827],
       [ 0.0468406 ,  0.01928278,  0.01705045, -0.02541938,  0.0238469 ,
         0.04348138, -0.00811531, -0.01292194